#ifndef GUARD_CONSTANTS_MOVES_H
#define GUARD_CONSTANTS_MOVES_H

enum __attribute__((packed)) Move
{
    MOVE_NONE = 0,
    //MOVE_POUND = 1,
    MOVE_STRIKE = 1,//replaces pound
    MOVE_KARATE_CHOP = 2,
    MOVE_SUPER_SLAP = 3, //digi move, replaces double slap
    //MOVE_DOUBLE_SLAP = 3,
    //MOVE_DOUBLESLAP = MOVE_DOUBLE_SLAP, // Pre-Gen VI name
    //MOVE_COMET_PUNCH = 4,
    MOVE_SHAMA_HAMMER = 4,//digi move, replaces comet punch
    //MOVE_MEGA_PUNCH = 5,
    MOVE_MEGATON_PUNCH = 5,
    MOVE_PAY_DAY = 6,
    MOVE_FIRE_PUNCH = 7,
    //MOVE_ICE_PUNCH = 8,
    MOVE_SNOW_GOBLI_VOLT = 8,//digi move, replaces ice punch
    //MOVE_THUNDER_PUNCH = 9,
    //MOVE_THUNDERPUNCH = MOVE_THUNDER_PUNCH, // Pre-Gen VI name
    MOVE_THUNDER_STRIKE = 9,//replaces thunder punch
    //MOVE_SCRATCH = 10,
    MOVE_NAIL_SCRATCH = 10, // replaces scratch
    MOVE_VISE_GRIP = 11,
    MOVE_VICEGRIP = MOVE_VISE_GRIP, // Pre-Gen VI name
    MOVE_VICE_GRIP = MOVE_VISE_GRIP, // Pre-Gen VIII name
    MOVE_GUILLOTINE = 12,
    MOVE_RAZOR_WIND = 13,
    MOVE_SWORDS_DANCE = 14,
    //MOVE_CUT = 15,
    MOVE_SCISSOR_ATTACK = 15,//digi move, replaces cut
    //MOVE_GUST = 16,
    MOVE_AIR_BUBBLES = 16,//replaces gust
    MOVE_WING_ATTACK = 17,
    MOVE_WHIRLWIND = 18,
    MOVE_FLY = 19,
    MOVE_BIND = 20,
    //MOVE_SLAM = 21,
    MOVE_HEAVY_STRIKE = 21,//replaces slam
    //MOVE_VINE_WHIP = 22,
    MOVE_THORN_STRIKE = 22,//replaces vine whip
    MOVE_STOMP = 23,
    MOVE_DOUBLE_KICK = 24,
    MOVE_MEGA_KICK = 25,
    MOVE_JUMP_KICK = 26,
    MOVE_ROLLING_KICK = 27,
    MOVE_SAND_ATTACK = 28,
    MOVE_HEADBUTT = 29,
    MOVE_HORN_ATTACK = 30,
    MOVE_FURY_ATTACK = 31,
    MOVE_HORN_DRILL = 32,
    MOVE_TACKLE = 33,
    MOVE_BODY_SLAM = 34,
    MOVE_WRAP = 35,
    MOVE_TAKE_DOWN = 36,
    MOVE_THRASH = 37,
    MOVE_DOUBLE_EDGE = 38,
    MOVE_TAIL_WHIP = 39,
    //MOVE_POISON_STING = 40,
    MOVE_DANGER_STING = 40,//digi move, replaces poison sting
    MOVE_TWINEEDLE = 41,
    MOVE_PIN_MISSILE = 42,
    //MOVE_LEER = 43,
    MOVE_GUARD_BREAK = 43,//digi move, replaces leer
    MOVE_BITE = 44,
    //MOVE_GROWL = 45,
    MOVE_BAD_MANNERS = 45,//digi move, replaces growl
    MOVE_ROAR = 46, 
    //MOVE_SING = 47,
    MOVE_LULLABY_BUBBLE = 47,//digi move, replaces sing
    MOVE_SUPERSONIC = 48,
    MOVE_SONIC_BOOM = 49,
    MOVE_SONICBOOM = MOVE_SONIC_BOOM, // Pre-Gen VI name
    MOVE_DISABLE = 50,
    //MOVE_ACID = 51,
    MOVE_POOP_THROW = 51, // Digimon move
    //MOVE_EMBER = 52,
    MOVE_SPITFIRE = 52, // Digimon move
    MOVE_FLAMETHROWER = 53,
    MOVE_MIST = 54,
    MOVE_WATER_GUN = 55,
    MOVE_HYDRO_PUMP = 56,
    //MOVE_SURF = 57,
    MOVE_TIDAL_STREAM = 57,//digi move, replaces surf
    MOVE_ICE_BEAM = 58,
    MOVE_BLIZZARD = 59,
    MOVE_PSYBEAM = 60,
    //MOVE_BUBBLE_BEAM = 61,
    //MOVE_BUBBLEBEAM = MOVE_BUBBLE_BEAM, // Pre-Gen VI name
    MOVE_BUBBLE_BREATH = 61, // Digimon move, replaces bubble beam
    MOVE_AURORA_FREEZE = 62, //digi move, replaces aurora beam
    //MOVE_AURORA_BEAM = 62,
    MOVE_HYPER_BEAM = 63,
    //MOVE_PECK = 64,
    MOVE_WIND_CLAW = 64,//digi move. replaces peck
    MOVE_DRILL_PECK = 65,
    MOVE_SUBMISSION = 66,
    MOVE_LOW_KICK = 67,
    MOVE_COUNTER = 68,
    MOVE_SEISMIC_TOSS = 69,
    MOVE_STRENGTH = 70,
    //MOVE_ABSORB = 71,
    MOVE_HUNGRY_HAND = 71,//digi move, replaces absorb
    MOVE_MEGA_DRAIN = 72,
    MOVE_LEECH_SEED = 73,
    //MOVE_GROWTH = 74,
    MOVE_MAGIC_CHARGE = 74,//digi move, replaces growth
    //MOVE_RAZOR_LEAF = 75,
    MOVE_BIO_HAZARD = 75, // Digimon move, replaces razor leaf
    MOVE_SOLAR_BEAM = 76,
    MOVE_SOLARBEAM = MOVE_SOLAR_BEAM, // Pre-Gen VI name
    MOVE_POISON_POWDER = 77, //digi move. unchanged from vanilla
    MOVE_POISONPOWDER = MOVE_POISON_POWDER, // Pre-Gen VI name
    MOVE_STUN_SPORE = 78,
    MOVE_SLEEP_POWDER = 79,
    MOVE_PETAL_DANCE = 80,
    //MOVE_STRING_SHOT = 81,
    MOVE_ELECTRO_THREAD = 81, // Digimon move, replaces string shot
    MOVE_DRAGON_RAGE = 82,
    MOVE_FIRE_SPIN = 83,
    //MOVE_THUNDER_SHOCK = 84,
    //MOVE_THUNDERSHOCK = MOVE_THUNDER_SHOCK, // Pre-Gen VI name
    MOVE_HERTZ_HOWL = 84, // Digimon move
    MOVE_THUNDERBOLT = 85,
    //MOVE_THUNDER_WAVE = 86,
    MOVE_ELECTRIC_CLOUD = 86,//digi move, replaces thunder wave
    MOVE_THUNDER = 87,
    //MOVE_ROCK_THROW = 88,
    MOVE_COMET_HAMMER = 88,// digimon move, replaces rock throw
    MOVE_EARTHQUAKE = 89,
    MOVE_FISSURE = 90,
    MOVE_DIG = 91,
    MOVE_TOXIC = 92,
    MOVE_CONFUSION = 93,
    MOVE_PSYCHIC = 94,
    //MOVE_HYPNOSIS = 95,
    MOVE_IDLE_BUBBLE = 95, // Digimon move, replaces hypnosis
    MOVE_MEDITATE = 96,
    //MOVE_AGILITY = 97,
    MOVE_SPEED_CHARGE = 97,//digi move, replaces agility
    //MOVE_QUICK_ATTACK = 98,
    MOVE_SONIC_JAB = 98,
    MOVE_RAGE = 99,
    MOVE_TELEPORT = 100,
    //MOVE_NIGHT_SHADE = 101,
    MOVE_NIGHTMARE_SYNDROME = 101, // Digimon move
    MOVE_MIMIC = 102,
    MOVE_SCREECH = 103,
    MOVE_DOUBLE_TEAM = 104,
    MOVE_RECOVER = 105,
    //MOVE_HARDEN = 106,
    MOVE_GUARD_CHARGE = 106,//digi move, replaces harden
    //MOVE_MINIMIZE = 107,
    MOVE_MASS_MORPH = 107,//digi move, replaces minimize
    MOVE_SMOKESCREEN = 108,
    //MOVE_CONFUSE_RAY = 109,//digi move, replaces confuse ray
    MOVE_BLACKOUT = 109,
    MOVE_WITHDRAW = 110,
    MOVE_DEFENSE_CURL = 111,
    MOVE_BARRIER = 112,
    MOVE_LIGHT_SCREEN = 113,
    MOVE_HAZE = 114,
    //MOVE_REFLECT = 115,
    MOVE_GUARD_FIELD = 115,//digi move, replaces reflect
    //MOVE_FOCUS_ENERGY = 116,
    MOVE_CRITICAL_CHARGE = 116,//digi move, replaces focus energy
    MOVE_BIDE = 117,
    MOVE_METRONOME = 118,
    MOVE_MIRROR_MOVE = 119,
    MOVE_SELF_DESTRUCT = 120,
    MOVE_SELFDESTRUCT = MOVE_SELF_DESTRUCT, // Pre-Gen VI name
    //MOVE_EGG_BOMB = 121,
    MOVE_CHEESE_BOMB = 121, // Digimon move
    //MOVE_LICK = 122,
    MOVE_DARK_SPIRIT = 122,//digi move, replaces lick
    //MOVE_SMOG = 123,
    MOVE_GLOOM_DUST = 123, // Digimon move, replaces smog
    //MOVE_SLUDGE = 124,
    MOVE_VENOM_TRAP = 124, // Digimon move, replaces sludge
    MOVE_BONE_CLUB = 125,
    MOVE_FIRE_BLAST = 126,
    MOVE_WATERFALL = 127,// digi move. unchanged from vanilla
    MOVE_CLAMP = 128,
    MOVE_SWIFT = 129,
    MOVE_SKULL_BASH = 130,
    MOVE_SPIKE_CANNON = 131,
    //MOVE_CONSTRICT = 132,
    MOVE_SPEED_BREAK = 132,//digi move, replaces constrict
    MOVE_AMNESIA = 133,
    MOVE_KINESIS = 134,
    MOVE_SOFT_BOILED = 135,
    MOVE_SOFTBOILED = MOVE_SOFT_BOILED, // Pre-Gen VI name
    MOVE_HIGH_JUMP_KICK = 136,
    MOVE_HI_JUMP_KICK = MOVE_HIGH_JUMP_KICK, // Pre-Gen VI name
    MOVE_GLARE = 137,
    MOVE_DREAM_EATER = 138,
    MOVE_POISON_GAS = 139,
    MOVE_BARRAGE = 140,
    MOVE_LEECH_LIFE = 141,
    MOVE_LOVELY_KISS = 142,
    MOVE_SKY_ATTACK = 143,
    MOVE_TRANSFORM = 144,
    //MOVE_BUBBLE = 145,
    MOVE_BUBBLES = 145, // Digimon move
    MOVE_DIZZY_PUNCH = 146,
    MOVE_SPORE = 147,
    MOVE_FLASH = 148, //digi move. does damage as well now
    //MOVE_PSYWAVE = 149,
    MOVE_LIGHT_SOUL = 149,//digi move, replaces psywave
    MOVE_SPLASH = 150,// digi move. does damage now. otherwise unchanged. 
    MOVE_ACID_ARMOR = 151,
    MOVE_CRABHAMMER = 152,
    MOVE_EXPLOSION = 153,
    MOVE_FURY_SWIPES = 154,
    MOVE_BONEMERANG = 155,
    MOVE_REST = 156,
    MOVE_ROCK_SLIDE = 157,
    MOVE_HYPER_FANG = 158,
    //MOVE_SHARPEN = 159,
    MOVE_ATTACK_CHARGE = 159,// Digimon move, replaces sharpen
    MOVE_CONVERSION = 160,
    MOVE_TRI_ATTACK = 161,
    MOVE_SUPER_FANG = 162,
    MOVE_SLASH = 163,
    MOVE_SUBSTITUTE = 164,
    MOVE_STRUGGLE = 165,
    MOVES_COUNT_GEN1,

    // Gen 2
    MOVE_SKETCH = MOVES_COUNT_GEN1,
    MOVE_TRIPLE_KICK = 167,
    MOVE_THIEF = 168,
    //MOVE_SPIDER_WEB = 169,
    MOVE_STICKY_NET = 169,//digi move, replaces spider web
    MOVE_MIND_READER = 170,
    MOVE_NIGHTMARE = 171,
    //MOVE_FLAME_WHEEL = 172,
    MOVE_GOBLIN_STRIKE = 172,//digi move, replaces flame wheel
    MOVE_SNORE = 173,
    MOVE_CURSE = 174,
    MOVE_FLAIL = 175,
    MOVE_CONVERSION_2 = 176,
    MOVE_AEROBLAST = 177,
    MOVE_COTTON_SPORE = 178,
    MOVE_REVERSAL = 179,
    MOVE_SPITE = 180,
    MOVE_FROZEN_WIND = 181,//digi move, replaces powder snow
    //MOVE_POWDER_SNOW = 181,
    MOVE_PROTECT = 182,
    //MOVE_MACH_PUNCH = 183,
    MOVE_MACH_JAB = 183,//digi move. replaces mach punch
    MOVE_SCARY_FACE = 184,
    //MOVE_FEINT_ATTACK = 185,
    //MOVE_FAINT_ATTACK = MOVE_FEINT_ATTACK, // Pre-Gen VI name
    MOVE_HELL_CRUSHER = 185,//digi move, faint attack
    MOVE_SWEET_KISS = 186,
    MOVE_BELLY_DRUM = 187,
    MOVE_SLUDGE_BOMB = 188,
    MOVE_MUD_SLAP = 189,
    MOVE_OCTAZOOKA = 190,
    MOVE_SPIKES = 191,
    MOVE_ZAP_CANNON = 192,
    MOVE_FORESIGHT = 193,
    MOVE_DESTINY_BOND = 194,
    MOVE_PERISH_SONG = 195,
    //MOVE_ICY_WIND = 196,
    MOVE_ADHESIVE_BUBBLE = 196, //replaces icy wind
    MOVE_DETECT = 197,
    MOVE_BONE_RUSH = 198,
    MOVE_LOCK_ON = 199,
    MOVE_OUTRAGE = 200,
    MOVE_SANDSTORM = 201,
    MOVE_GIGA_DRAIN = 202,
    MOVE_ENDURE = 203,
    MOVE_CHARM = 204,
    //MOVE_ROLLOUT = 205,
    MOVE_SPIN_ATTACK = 205,//digi move, replaces rollout
    MOVE_FALSE_SWIPE = 206,
    MOVE_SWAGGER = 207,
    MOVE_MILK_DRINK = 208,
    //MOVE_SPARK = 209,
    MOVE_MINI_SCISSOR_CLAW = 209,//digi move, replaces spark
    MOVE_FURY_CUTTER = 210,
    MOVE_STEEL_WING = 211,
    MOVE_MEAN_LOOK = 212,
    MOVE_ATTRACT = 213,
    MOVE_SLEEP_TALK = 214,
    MOVE_HEAL_BELL = 215,
    MOVE_RETURN = 216,
    MOVE_PRESENT = 217,
    MOVE_FRUSTRATION = 218,
    MOVE_SAFEGUARD = 219,
    MOVE_PAIN_SPLIT = 220,
    MOVE_SACRED_FIRE = 221,
    MOVE_MAGNITUDE = 222,
    MOVE_DYNAMIC_PUNCH = 223,
    MOVE_DYNAMICPUNCH = MOVE_DYNAMIC_PUNCH, // Pre-Gen VI name
    MOVE_MEGAHORN = 224,
    MOVE_DRAGON_BREATH = 225,
    MOVE_DRAGONBREATH = MOVE_DRAGON_BREATH, // Pre-Gen VI name
    MOVE_BATON_PASS = 226,
    MOVE_ENCORE = 227,
    MOVE_PURSUIT = 228,
    //MOVE_RAPID_SPIN = 229,
    MOVE_SPIRAL_EDGE = 229,//digi move. replaces spiral edge
    MOVE_SWEET_SCENT = 230,
    MOVE_IRON_TAIL = 231,
    //MOVE_METAL_CLAW = 232,
    MOVE_IRON_SLASH = 232,//digi move, replaces metal claw
    MOVE_VITAL_THROW = 233,
    MOVE_MORNING_SUN = 234,
    MOVE_SYNTHESIS = 235,
    MOVE_MOONLIGHT = 236,
    MOVE_HIDDEN_POWER = 237,
    MOVE_CROSS_CHOP = 238,
    //MOVE_TWISTER = 239,
    MOVE_DARK_TWISTER = 239,//digi move, replaces twister
    //MOVE_RAIN_DANCE = 240,
    MOVE_HEAVY_RAIN = 240,//digi move, replaces rain dance
    MOVE_SUNNY_DAY = 241,
    MOVE_CRUNCH = 242,
    MOVE_MIRROR_COAT = 243,
    MOVE_PSYCH_UP = 244,
    MOVE_EXTREME_SPEED = 245,
    MOVE_EXTREMESPEED = MOVE_EXTREME_SPEED, // Pre-Gen VI name
    //MOVE_ANCIENT_POWER = 246,
    //MOVE_ANCIENTPOWER = MOVE_ANCIENT_POWER, // Pre-Gen VI name
    MOVE_GAIA_BLAST = 246,//digi move, replaces ancient power
    MOVE_SHADOW_BALL = 247,
    MOVE_FUTURE_SIGHT = 248,
    MOVE_ROCK_SMASH = 249,
    MOVE_WHIRLPOOL = 250,
    MOVE_BEAT_UP = 251,
    MOVES_COUNT_GEN2,

    // Gen 3
    MOVE_FAKE_OUT = MOVES_COUNT_GEN2,
    MOVE_UPROAR = 253,
    MOVE_STOCKPILE = 254,
    MOVE_SPIT_UP = 255,
    MOVE_SWALLOW = 256,
    //MOVE_HEAT_WAVE = 257,
    MOVE_FRIENDLY_FIRE = 257,
    MOVE_HAIL = 258,
    MOVE_TORMENT = 259,
    MOVE_FLATTER = 260,
    //MOVE_WILL_O_WISP = 261,
    MOVE_PANIC_WISP = 261,//digi move, replaces will-o-wisp
    MOVE_MEMENTO = 262,
    MOVE_FACADE = 263,
    MOVE_FOCUS_PUNCH = 264,
    MOVE_SMELLING_SALTS = 265,
    MOVE_SMELLINGSALT = MOVE_SMELLING_SALTS, // Pre-Gen VI name
    MOVE_FOLLOW_ME = 266,
    MOVE_NATURE_POWER = 267,
    MOVE_CHARGE = 268,
    MOVE_TAUNT = 269,
    MOVE_HELPING_HAND = 270,
    MOVE_TRICK = 271,
    MOVE_ROLE_PLAY = 272,
    MOVE_WISH = 273,
    MOVE_ASSIST = 274,
    MOVE_INGRAIN = 275,
    MOVE_SUPERPOWER = 276,
    MOVE_MAGIC_COAT = 277,
    MOVE_RECYCLE = 278,
    MOVE_REVENGE = 279,
    MOVE_BRICK_BREAK = 280,
    MOVE_YAWN = 281,
    MOVE_KNOCK_OFF = 282,
    MOVE_ENDEAVOR = 283,
    MOVE_ERUPTION = 284,
    MOVE_SKILL_SWAP = 285,
    MOVE_IMPRISON = 286,
    //MOVE_REFRESH = 287,
    MOVE_MEDITATOR = 287,//digi move. replaces refresh
    MOVE_GRUDGE = 288,
    MOVE_SNATCH = 289,
    MOVE_SECRET_POWER = 290,
    MOVE_DIVE = 291,
    MOVE_ARM_THRUST = 292,
    MOVE_CAMOUFLAGE = 293,
    MOVE_TAIL_GLOW = 294,
    MOVE_LUSTER_PURGE = 295,
    MOVE_MIST_BALL = 296,
    //MOVE_FEATHER_DANCE = 297,
    //MOVE_FEATHERDANCE = MOVE_FEATHER_DANCE, // Pre-Gen VI name
    MOVE_WING_SHOES = 297, //digi move, replaces feather dance
    MOVE_TEETER_DANCE = 298,
    MOVE_BLAZE_KICK = 299,
    MOVE_MUD_SPORT = 300,
    //MOVE_ICE_BALL = 301,
    MOVE_ICY_GLIDE = 301, //digi move, replaces ice ball
    MOVE_NEEDLE_ARM = 302,
    MOVE_SLACK_OFF = 303,
    MOVE_HYPER_VOICE = 304,
    //MOVE_POISON_FANG = 305,
    MOVE_POISON_CLAW = 305, // Digimon move, replaces poison fang
    MOVE_CRUSH_CLAW = 306,
    MOVE_BLAST_BURN = 307,
    MOVE_HYDRO_CANNON = 308,
    MOVE_METEOR_MASH = 309,
    //MOVE_ASTONISH = 310,
    MOVE_CANDLE_SLASH = 310, // Digimon move
    MOVE_WEATHER_BALL = 311,
    MOVE_AROMATHERAPY = 312,
    MOVE_FAKE_TEARS = 313,
    //MOVE_AIR_CUTTER = 314,
    MOVE_AIR_SHOT = 314, // Digimon move, replaces air cutter
    MOVE_OVERHEAT = 315,
    MOVE_ODOR_SLEUTH = 316,
    MOVE_ROCK_TOMB = 317,
    MOVE_SILVER_WIND = 318,
    MOVE_METAL_SOUND = 319,
    MOVE_GRASS_WHISTLE = 320,
    MOVE_GRASSWHISTLE = MOVE_GRASS_WHISTLE, // Pre-Gen VI name
    MOVE_TICKLE = 321,
    MOVE_COSMIC_POWER = 322,
    MOVE_WATER_SPOUT = 323,
    MOVE_SIGNAL_BEAM = 324,
    MOVE_SHADOW_PUNCH = 325,
    MOVE_EXTRASENSORY = 326,
    MOVE_SKY_UPPERCUT = 327,
    MOVE_SAND_TOMB = 328,
    MOVE_SHEER_COLD = 329,
    MOVE_MUDDY_WATER = 330,
    MOVE_BULLET_SEED = 331,
    MOVE_AERIAL_ACE = 332,
    //MOVE_ICICLE_SPEAR = 333,
    MOVE_HAIL_SPEAR = 333,//digi move, replaces icicle spear
    MOVE_IRON_DEFENSE = 334,
    MOVE_BLOCK = 335,
    MOVE_HOWL = 336,
    MOVE_DRAGON_CLAW = 337,
    MOVE_FRENZY_PLANT = 338,
    MOVE_BULK_UP = 339,
    MOVE_BOUNCE = 340,
    MOVE_MUD_SHOT = 341,
    MOVE_POISON_TAIL = 342,
    MOVE_COVET = 343,
    MOVE_VOLT_TACKLE = 344,
    //MOVE_MAGICAL_LEAF = 345,
    MOVE_CRESCENT_LEAF = 345,
    //MOVE_WATER_SPORT = 346,
    MOVE_AQUA_MAGIC = 346,//digi move, replaces water sport
    MOVE_CALM_MIND = 347,
    MOVE_LEAF_BLADE = 348,
    MOVE_DRAGON_DANCE = 349,
    MOVE_ROCK_BLAST = 350,
    //MOVE_SHOCK_WAVE = 351,
    MOVE_ELECTRO_SHOCK = 351, // Digimon move
    //MOVE_WATER_PULSE = 352,
    MOVE_WATER_TOWER = 352,//digi move, replaces water pulse
    MOVE_DOOM_DESIRE = 353,
    MOVE_PSYCHO_BOOST = 354,
    MOVES_COUNT_GEN3,

    // Gen 4
    MOVE_ROOST = MOVES_COUNT_GEN3,
    MOVE_GRAVITY = 356,
    MOVE_MIRACLE_EYE = 357,
    MOVE_WAKE_UP_SLAP = 358,
    MOVE_HAMMER_ARM = 359,
    MOVE_GYRO_BALL = 360,
    MOVE_HEALING_WISH = 361,
    MOVE_BRINE = 362,
    MOVE_NATURAL_GIFT = 363,
    MOVE_FEINT = 364,
    MOVE_PLUCK = 365,
    MOVE_TAILWIND = 366,
    MOVE_ACUPRESSURE = 367,
    MOVE_METAL_BURST = 368,
    MOVE_U_TURN = 369,
    MOVE_CLOSE_COMBAT = 370,
    MOVE_PAYBACK = 371,
    MOVE_ASSURANCE = 372,
    MOVE_EMBARGO = 373,
    MOVE_FLING = 374,
    MOVE_PSYCHO_SHIFT = 375,
    MOVE_TRUMP_CARD = 376,
    MOVE_HEAL_BLOCK = 377,
    MOVE_WRING_OUT = 378,
    MOVE_POWER_TRICK = 379,
    MOVE_GASTRO_ACID = 380,
    MOVE_LUCKY_CHANT = 381,
    MOVE_ME_FIRST = 382,
    MOVE_COPYCAT = 383,
    MOVE_POWER_SWAP = 384,
    MOVE_GUARD_SWAP = 385,
    MOVE_PUNISHMENT = 386,
    MOVE_LAST_RESORT = 387,
    MOVE_WORRY_SEED = 388,
    MOVE_SUCKER_PUNCH = 389,
    MOVE_TOXIC_SPIKES = 390,
    MOVE_HEART_SWAP = 391,
    MOVE_AQUA_RING = 392,
    MOVE_MAGNET_RISE = 393,
    MOVE_FLARE_BLITZ = 394,
    MOVE_FORCE_PALM = 395,
    MOVE_AURA_SPHERE = 396,
    MOVE_ROCK_POLISH = 397,
    //MOVE_POISON_JAB = 398,
    MOVE_POISON_IVY = 398,//digi move, replaces poison jab
    MOVE_DARK_PULSE = 399,
    MOVE_NIGHT_SLASH = 400,
    MOVE_AQUA_TAIL = 401,
    MOVE_SEED_BOMB = 402,
    //MOVE_AIR_SLASH = 403,
    MOVE_WIND_CUTTER = 403,
    MOVE_X_SCISSOR = 404,
    MOVE_BUG_BUZZ = 405,
    MOVE_DRAGON_PULSE = 406,
    MOVE_DRAGON_RUSH = 407,
    MOVE_POWER_GEM = 408,
    MOVE_DRAIN_PUNCH = 409,
    MOVE_VACUUM_WAVE = 410,
    MOVE_FOCUS_BLAST = 411,
    MOVE_ENERGY_BALL = 412,
    MOVE_BRAVE_BIRD = 413,
    MOVE_EARTH_POWER = 414,
    MOVE_SWITCHEROO = 415,
    MOVE_GIGA_IMPACT = 416,
    MOVE_NASTY_PLOT = 417,
    MOVE_BULLET_PUNCH = 418,
    //MOVE_AVALANCHE = 419,
    MOVE_DIAMOND_DUST = 419,
    //MOVE_ICE_SHARD = 420,
    MOVE_FROZEN_BULLET = 420,//digi move, replaces ice shard
    MOVE_SHADOW_CLAW = 421,
    MOVE_THUNDER_FANG = 422,
    MOVE_ICE_FANG = 423,
    MOVE_FIRE_FANG = 424,
    MOVE_SHADOW_SNEAK = 425,
    MOVE_MUD_BOMB = 426,
    MOVE_PSYCHO_CUT = 427,
    MOVE_ZEN_HEADBUTT = 428,
    MOVE_MIRROR_SHOT = 429,
    MOVE_FLASH_CANNON = 430,
    MOVE_ROCK_CLIMB = 431,
    MOVE_DEFOG = 432,
    MOVE_TRICK_ROOM = 433,
    MOVE_DRACO_METEOR = 434,
    MOVE_DISCHARGE = 435,
    MOVE_LAVA_PLUME = 436,
    MOVE_LEAF_STORM = 437,
    MOVE_POWER_WHIP = 438,
    MOVE_ROCK_WRECKER = 439,
    MOVE_CROSS_POISON = 440,
    MOVE_GUNK_SHOT = 441,
    MOVE_IRON_HEAD = 442,
    //MOVE_MAGNET_BOMB = 443,
    MOVE_DIS_ASSEMBLER = 443,//digi move, replaces magnet bomb
    MOVE_STONE_EDGE = 444,
    MOVE_CAPTIVATE = 445,
    MOVE_STEALTH_ROCK = 446,
    MOVE_GRASS_KNOT = 447,
    MOVE_CHATTER = 448,
    MOVE_JUDGMENT = 449,
    MOVE_BUG_BITE = 450,
    MOVE_CHARGE_BEAM = 451,
    MOVE_WOOD_HAMMER = 452,
    MOVE_AQUA_JET = 453,
    //MOVE_ATTACK_ORDER = 454,
    MOVE_INSECT_HORDE = 454,//digi move, replaces attack order
    MOVE_DEFEND_ORDER = 455,
    MOVE_HEAL_ORDER = 456,
    MOVE_HEAD_SMASH = 457,
    MOVE_DOUBLE_HIT = 458,
    MOVE_ROAR_OF_TIME = 459,
    MOVE_SPACIAL_REND = 460,
    MOVE_LUNAR_DANCE = 461,
    MOVE_CRUSH_GRIP = 462,
    MOVE_MAGMA_STORM = 463,
    MOVE_DARK_VOID = 464,
    MOVE_SEED_FLARE = 465,
    MOVE_OMINOUS_WIND = 466,
    MOVE_SHADOW_FORCE = 467,
    MOVES_COUNT_GEN4,

    // Gen 5
    MOVE_HONE_CLAWS = MOVES_COUNT_GEN4,
    MOVE_WIDE_GUARD = 469,
    MOVE_GUARD_SPLIT = 470,
    MOVE_POWER_SPLIT = 471,
    MOVE_WONDER_ROOM = 472,
    MOVE_PSYSHOCK = 473,
    MOVE_VENOSHOCK = 474,
    MOVE_AUTOTOMIZE = 475,
    MOVE_RAGE_POWDER = 476,
    MOVE_TELEKINESIS = 477,
    MOVE_MAGIC_ROOM = 478,
    //MOVE_SMACK_DOWN = 479,
    MOVE_ROCK_FIST = 479,//digi move, replaces smack down
    MOVE_STORM_THROW = 480,
    //MOVE_FLAME_BURST = 481,
    MOVE_FIRE_BALL = 481,// digimon move
    MOVE_SLUDGE_WAVE = 482,
    MOVE_QUIVER_DANCE = 483,
    MOVE_HEAVY_SLAM = 484,
    MOVE_SYNCHRONOISE = 485,
    MOVE_ELECTRO_BALL = 486,
    MOVE_SOAK = 487,
    MOVE_FLAME_CHARGE = 488,
    MOVE_COIL = 489,
    MOVE_LOW_SWEEP = 490,
    MOVE_ACID_SPRAY = 491,
    MOVE_FOUL_PLAY = 492,
    MOVE_SIMPLE_BEAM = 493,
    MOVE_ENTRAINMENT = 494,
    MOVE_AFTER_YOU = 495,
    MOVE_ROUND = 496,
    MOVE_ECHOED_VOICE = 497,
    MOVE_CHIP_AWAY = 498,
    MOVE_CLEAR_SMOG = 499,
    MOVE_STORED_POWER = 500,
    MOVE_QUICK_GUARD = 501,
    MOVE_ALLY_SWITCH = 502,
    MOVE_SCALD = 503,
    MOVE_SHELL_SMASH = 504,
    //MOVE_HEAL_PULSE = 505,
    MOVE_HEAL = 505,
    MOVE_HEX = 506,
    MOVE_SKY_DROP = 507,
    MOVE_SHIFT_GEAR = 508,
    MOVE_CIRCLE_THROW = 509,
    //MOVE_INCINERATE = 510,
    MOVE_BLUE_BLASTER = 510,//digi move, replaces incinerate
    MOVE_QUASH = 511,
    MOVE_ACROBATICS = 512,
    MOVE_REFLECT_TYPE = 513,
    MOVE_RETALIATE = 514,
    MOVE_FINAL_GAMBIT = 515,
    MOVE_BESTOW = 516,
    MOVE_INFERNO = 517,
    MOVE_WATER_PLEDGE = 518,
    MOVE_FIRE_PLEDGE = 519,
    MOVE_GRASS_PLEDGE = 520,
    MOVE_VOLT_SWITCH = 521,
    MOVE_STRUGGLE_BUG = 522,
    MOVE_BULLDOZE = 523,
    MOVE_FROST_BREATH = 524,
    MOVE_DRAGON_TAIL = 525,
    //MOVE_WORK_UP = 526,
    MOVE_MUSCLE_CHARGE = 526,//digi move, replaces work up
    MOVE_ELECTROWEB = 527,
    MOVE_WILD_CHARGE = 528,
    MOVE_DRILL_RUN = 529,
    MOVE_DUAL_CHOP = 530,
    MOVE_HEART_STAMP = 531,
    MOVE_HORN_LEECH = 532,
    MOVE_SACRED_SWORD = 533,
    MOVE_RAZOR_SHELL = 534,
    MOVE_HEAT_CRASH = 535,
    MOVE_LEAF_TORNADO = 536,
    MOVE_STEAMROLLER = 537,
    MOVE_COTTON_GUARD = 538,
    MOVE_NIGHT_DAZE = 539,
    MOVE_PSYSTRIKE = 540,
    //MOVE_TAIL_SLAP = 541,
    MOVE_FOX_TAIL = 541, // Digimon move
    MOVE_HURRICANE = 542,//digi move. slightly altered from vanilla. 
    MOVE_HEAD_CHARGE = 543,
    //MOVE_GEAR_GRIND = 544,
    MOVE_COG_CRUSH = 544,
    MOVE_SEARING_SHOT = 545,
    MOVE_TECHNO_BLAST = 546,
    MOVE_RELIC_SONG = 547,
    MOVE_SECRET_SWORD = 548,
    MOVE_GLACIATE = 549,
    MOVE_BOLT_STRIKE = 550,
    MOVE_BLUE_FLARE = 551,
    MOVE_FIERY_DANCE = 552,
    MOVE_FREEZE_SHOCK = 553,
    MOVE_ICE_BURN = 554,
    MOVE_SNARL = 555,
    MOVE_ICICLE_CRASH = 556,
    MOVE_V_CREATE = 557,
    MOVE_FUSION_FLARE = 558,
    MOVE_FUSION_BOLT = 559,
    MOVES_COUNT_GEN5,

    // Gen 6
    MOVE_FLYING_PRESS = MOVES_COUNT_GEN5,
    MOVE_MAT_BLOCK = 561,
    MOVE_BELCH = 562,
    MOVE_ROTOTILLER = 563,
    MOVE_STICKY_WEB = 564,
    MOVE_FELL_STINGER = 565,
    MOVE_PHANTOM_FORCE = 566,
    MOVE_TRICK_OR_TREAT = 567,
    MOVE_NOBLE_ROAR = 568,
    MOVE_ION_DELUGE = 569,
    MOVE_PARABOLIC_CHARGE = 570,
    MOVE_FORESTS_CURSE = 571,
    MOVE_PETAL_BLIZZARD = 572,
    MOVE_FREEZE_DRY = 573,
    //MOVE_DISARMING_VOICE = 574,
    MOVE_HOLY_LIGHT = 574,//digi move, replaces disarming voice
    MOVE_PARTING_SHOT = 575,
    MOVE_TOPSY_TURVY = 576,
    MOVE_DRAINING_KISS = 577,
    MOVE_CRAFTY_SHIELD = 578,
    MOVE_FLOWER_SHIELD = 579,
    MOVE_GRASSY_TERRAIN = 580,
    MOVE_MISTY_TERRAIN = 581,
    MOVE_ELECTRIFY = 582,
    MOVE_PLAY_ROUGH = 583,
    MOVE_FAIRY_WIND = 584,
    MOVE_MOONBLAST = 585,
    MOVE_BOOMBURST = 586,
    MOVE_FAIRY_LOCK = 587,
    MOVE_KINGS_SHIELD = 588,
    MOVE_PLAY_NICE = 589,
    MOVE_CONFIDE = 590,
    MOVE_DIAMOND_STORM = 591,
    MOVE_STEAM_ERUPTION = 592,
    MOVE_HYPERSPACE_HOLE = 593,
    //MOVE_WATER_SHURIKEN = 594,
    MOVE_MARCHING_FISH = 594,//digi move, replaces water shuriken
    MOVE_MYSTICAL_FIRE = 595,
    MOVE_SPIKY_SHIELD = 596,
    //MOVE_AROMATIC_MIST = 597,
    MOVE_MENTAL_CHARGE = 597,//digi move, replaces aromatic mist
    MOVE_EERIE_IMPULSE = 598,
    MOVE_VENOM_DRENCH = 599,
    MOVE_POWDER = 600,
    MOVE_GEOMANCY = 601,
    MOVE_MAGNETIC_FLUX = 602,
    MOVE_HAPPY_HOUR = 603,
    MOVE_ELECTRIC_TERRAIN = 604,
    MOVE_DAZZLING_GLEAM = 605,
    MOVE_CELEBRATE = 606,
    MOVE_HOLD_HANDS = 607,
    MOVE_BABY_DOLL_EYES = 608,
    MOVE_NUZZLE = 609,
    MOVE_HOLD_BACK = 610,
    MOVE_INFESTATION = 611,
    MOVE_POWER_UP_PUNCH = 612,
    MOVE_OBLIVION_WING = 613,
    MOVE_THOUSAND_ARROWS = 614,
    MOVE_THOUSAND_WAVES = 615,
    MOVE_LANDS_WRATH = 616,
    MOVE_LIGHT_OF_RUIN = 617,
    // ORAS Moves
    MOVE_ORIGIN_PULSE = 618,
    MOVE_PRECIPICE_BLADES = 619,
    MOVE_DRAGON_ASCENT = 620,
    MOVE_HYPERSPACE_FURY = 621,
    MOVES_COUNT_GEN6,

    // Gen 7
    MOVE_SHORE_UP = MOVES_COUNT_GEN6,
    MOVE_FIRST_IMPRESSION = 623,
    MOVE_BANEFUL_BUNKER = 624,
    MOVE_SPIRIT_SHACKLE = 625,
    MOVE_DARKEST_LARIAT = 626,
    MOVE_SPARKLING_ARIA = 627,
    MOVE_ICE_HAMMER = 628,
    MOVE_FLORAL_HEALING = 629,
    MOVE_HIGH_HORSEPOWER = 630,
    MOVE_STRENGTH_SAP = 631,
    MOVE_SOLAR_BLADE = 632,
    MOVE_LEAFAGE = 633,
    MOVE_SPOTLIGHT = 634,
    MOVE_TOXIC_THREAD = 635,
    MOVE_LASER_FOCUS = 636,
    MOVE_GEAR_UP = 637,
    MOVE_THROAT_CHOP = 638,
    MOVE_POLLEN_PUFF = 639,
    MOVE_ANCHOR_SHOT = 640,
    MOVE_PSYCHIC_TERRAIN = 641,
    MOVE_LUNGE = 642,
    MOVE_FIRE_LASH = 643,
    MOVE_POWER_TRIP = 644,
    MOVE_BURN_UP = 645,
    MOVE_SPEED_SWAP = 646,
    MOVE_SMART_STRIKE = 647,
    MOVE_PURIFY = 648,
    MOVE_REVELATION_DANCE = 649,
    MOVE_CORE_ENFORCER = 650,
    MOVE_TROP_KICK = 651,
    MOVE_INSTRUCT = 652,
    MOVE_BEAK_BLAST = 653,
    MOVE_CLANGING_SCALES = 654,
    MOVE_DRAGON_HAMMER = 655,
    MOVE_BRUTAL_SWING = 656,
    MOVE_AURORA_VEIL = 657,
    MOVE_SHELL_TRAP = 658,
    MOVE_FLEUR_CANNON = 659,
    MOVE_PSYCHIC_FANGS = 660,
    MOVE_STOMPING_TANTRUM = 661,
    MOVE_SHADOW_BONE = 662,
    MOVE_ACCELEROCK = 663,
    MOVE_LIQUIDATION = 664,
    MOVE_PRISMATIC_LASER = 665,
    MOVE_SPECTRAL_THIEF = 666,
    MOVE_SUNSTEEL_STRIKE = 667,
    MOVE_MOONGEIST_BEAM = 668,
    MOVE_TEARFUL_LOOK = 669,
    MOVE_ZING_ZAP = 670,
    MOVE_NATURES_MADNESS = 671,
    MOVE_MULTI_ATTACK = 672,
    // USUM Moves
    MOVE_MIND_BLOWN = 673,
    MOVE_PLASMA_FISTS = 674,
    MOVE_PHOTON_GEYSER = 675,
    // LGPE Moves
    MOVE_ZIPPY_ZAP = 676,
    MOVE_SPLISHY_SPLASH = 677,
    MOVE_FLOATY_FALL = 678,
    MOVE_PIKA_PAPOW = 679,
    MOVE_BOUNCY_BUBBLE = 680,
    //MOVE_BUZZY_BUZZ = 681,
    MOVE_NANOBOT_BREAK = 681, //digi move, replaces buzzy buzz
    MOVE_SIZZLY_SLIDE = 682,
    MOVE_GLITZY_GLOW = 683,
    MOVE_BADDY_BAD = 684,
    MOVE_SAPPY_SEED = 685,
    //MOVE_FREEZY_FROST = 686,
    MOVE_ICE_STATUE = 686,//digi move, replaces freezy frost
    MOVE_SPARKLY_SWIRL = 687,
    MOVE_VEEVEE_VOLLEY = 688,
    //MOVE_DOUBLE_IRON_BASH = 689,
    MOVE_CRUSH_BLADE = 689,//digi move, replaces double iron bash
    MOVES_COUNT_GEN7,

    // Gen 8
    MOVE_DYNAMAX_CANNON = MOVES_COUNT_GEN7,
    MOVE_SNIPE_SHOT = 691,
    MOVE_JAW_LOCK = 692,
    MOVE_STUFF_CHEEKS = 693,
    MOVE_NO_RETREAT = 694,
    MOVE_TAR_SHOT = 695,
    MOVE_MAGIC_POWDER = 696,
    MOVE_DRAGON_DARTS = 697,
    MOVE_TEATIME = 698,
    MOVE_OCTOLOCK = 699,
    MOVE_BOLT_BEAK = 700,
    MOVE_FISHIOUS_REND = 701,
    MOVE_COURT_CHANGE = 702,
    MOVE_CLANGOROUS_SOUL = 703,
    MOVE_BODY_PRESS = 704,
    MOVE_DECORATE = 705,
    MOVE_DRUM_BEATING = 706,
    MOVE_SNAP_TRAP = 707,
    MOVE_PYRO_BALL = 708,
    MOVE_BEHEMOTH_BLADE = 709,
    MOVE_BEHEMOTH_BASH = 710,
    MOVE_AURA_WHEEL = 711,
    MOVE_BREAKING_SWIPE = 712,
    //MOVE_BRANCH_POKE = 713,
    MOVE_RAIN_OF_POLLEN = 713,//digi move, replaces branch poke
    MOVE_OVERDRIVE = 714,
    MOVE_APPLE_ACID = 715,
    MOVE_GRAV_APPLE = 716,
    MOVE_SPIRIT_BREAK = 717,
    MOVE_STRANGE_STEAM = 718,
    MOVE_LIFE_DEW = 719,
    MOVE_OBSTRUCT = 720,
    MOVE_FALSE_SURRENDER = 721,
    MOVE_METEOR_ASSAULT = 722,
    MOVE_ETERNABEAM = 723,
    MOVE_STEEL_BEAM = 724,
    // Isle of Armor Moves
    MOVE_EXPANDING_FORCE = 725,
    MOVE_STEEL_ROLLER = 726,
    MOVE_SCALE_SHOT = 727,
    MOVE_METEOR_BEAM = 728,
    MOVE_SHELL_SIDE_ARM = 729,
    MOVE_MISTY_EXPLOSION = 730,
    MOVE_GRASSY_GLIDE = 731,
    MOVE_RISING_VOLTAGE = 732,
    MOVE_TERRAIN_PULSE = 733,
    MOVE_SKITTER_SMACK = 734,
    MOVE_BURNING_JEALOUSY = 735,
    MOVE_LASH_OUT = 736,
    MOVE_POLTERGEIST = 737,
    MOVE_CORROSIVE_GAS = 738,
    MOVE_COACHING = 739,
    MOVE_FLIP_TURN = 740,
    MOVE_TRIPLE_AXEL = 741,
    MOVE_DUAL_WINGBEAT = 742,
    MOVE_SCORCHING_SANDS = 743,
    MOVE_JUNGLE_HEALING = 744,
    MOVE_WICKED_BLOW = 745,
    MOVE_SURGING_STRIKES = 746,
    // Crown Tundra Moves
    MOVE_THUNDER_CAGE = 747,
    MOVE_DRAGON_ENERGY = 748,
    MOVE_FREEZING_GLARE = 749,
    MOVE_FIERY_WRATH = 750,
    MOVE_THUNDEROUS_KICK = 751,
    MOVE_GLACIAL_LANCE = 752,
    MOVE_ASTRAL_BARRAGE = 753,
    MOVE_EERIE_SPELL = 754,
    // Legends: Arceus Moves
    //MOVE_DIRE_CLAW = 755,
    MOVE_FUNGUS_CRUSHER = 755, //digi move, replaces dire claw
    MOVE_PSYSHIELD_BASH = 756,
    MOVE_POWER_SHIFT = 757,
    MOVE_STONE_AXE = 758,
    MOVE_SPRINGTIDE_STORM = 759,
    MOVE_MYSTICAL_POWER = 760,
    MOVE_RAGING_FURY = 761,
    MOVE_WAVE_CRASH = 762,
    MOVE_CHLOROBLAST = 763,
    MOVE_MOUNTAIN_GALE = 764,
    MOVE_VICTORY_DANCE = 765,
    MOVE_HEADLONG_RUSH = 766,
    MOVE_BARB_BARRAGE = 767,
    MOVE_ESPER_WING = 768,
    MOVE_BITTER_MALICE = 769,
    MOVE_SHELTER = 770,
    MOVE_TRIPLE_ARROWS = 771,
    MOVE_INFERNAL_PARADE = 772,
    MOVE_CEASELESS_EDGE = 773,
    MOVE_BLEAKWIND_STORM = 774,
    //MOVE_WILDBOLT_STORM = 775,
    MOVE_THUNDERSTORM = 775,//digi move, replaces wildbolt storm
    MOVE_SANDSEAR_STORM = 776,
    MOVE_LUNAR_BLESSING = 777,
    MOVE_TAKE_HEART = 778,
    MOVES_COUNT_GEN8,

    // Gen 9
    MOVE_TERA_BLAST = MOVES_COUNT_GEN8,
    MOVE_SILK_TRAP = 780,
    MOVE_AXE_KICK = 781,
    MOVE_LAST_RESPECTS = 782,
    MOVE_LUMINA_CRASH = 783,
    MOVE_ORDER_UP = 784,
    MOVE_JET_PUNCH = 785,
    MOVE_SPICY_EXTRACT = 786,
    MOVE_SPIN_OUT = 787,
    MOVE_POPULATION_BOMB = 788,
    MOVE_ICE_SPINNER = 789,
    MOVE_GLAIVE_RUSH = 790,
    MOVE_REVIVAL_BLESSING = 791,
    MOVE_SALT_CURE = 792,
    MOVE_TRIPLE_DIVE = 793,
    MOVE_MORTAL_SPIN = 794,
    MOVE_DOODLE = 795,
    MOVE_FILLET_AWAY = 796,
    MOVE_KOWTOW_CLEAVE = 797,
    MOVE_FLOWER_TRICK = 798,
    MOVE_TORCH_SONG = 799,
    MOVE_AQUA_STEP = 800,
    MOVE_RAGING_BULL = 801,
    MOVE_MAKE_IT_RAIN = 802,
    MOVE_RUINATION = 803,
    MOVE_COLLISION_COURSE = 804,
    MOVE_ELECTRO_DRIFT = 805,
    MOVE_SHED_TAIL = 806,
    MOVE_CHILLY_RECEPTION = 807,
    MOVE_TIDY_UP = 808,
    MOVE_SNOWSCAPE = 809,
    MOVE_POUNCE = 810,
    MOVE_TRAILBLAZE = 811,
    MOVE_CHILLING_WATER = 812,
    MOVE_HYPER_DRILL = 813,
    MOVE_TWIN_BEAM = 814,
    MOVE_RAGE_FIST = 815,
    MOVE_ARMOR_CANNON = 816,
    MOVE_BITTER_BLADE = 817,
    MOVE_DOUBLE_SHOCK = 818,
    MOVE_GIGATON_HAMMER = 819,
    MOVE_COMEUPPANCE = 820,
    MOVE_AQUA_CUTTER = 821,
    MOVE_BLAZING_TORQUE = 822,
    MOVE_WICKED_TORQUE = 823,
    MOVE_NOXIOUS_TORQUE = 824,
    MOVE_COMBAT_TORQUE = 825,
    MOVE_MAGICAL_TORQUE = 826,
    MOVE_PSYBLADE = 827,
    MOVE_HYDRO_STEAM = 828,
    // The Teal Mask Moves
    MOVE_BLOOD_MOON = 829,
    MOVE_MATCHA_GOTCHA = 830,
    MOVE_SYRUP_BOMB = 831,
    MOVE_IVY_CUDGEL = 832,
    // The Indigo Disk Moves
    MOVE_ELECTRO_SHOT = 833,
    MOVE_TERA_STARSTORM = 834,
    MOVE_FICKLE_BEAM = 835,
    //MOVE_BURNING_BULWARK = 836,
    MOVE_FIREWALL = 836,//digi move, replaces burning bulwark
    MOVE_THUNDERCLAP = 837,
    MOVE_MIGHTY_CLEAVE = 838,
    MOVE_TACHYON_CUTTER = 839,
    MOVE_HARD_PRESS = 840,
    MOVE_DRAGON_CHEER = 841,
    MOVE_ALLURING_VOICE = 842,
    MOVE_TEMPER_FLARE = 843,
    MOVE_SUPERCELL_SLAM = 844,
    MOVE_PSYCHIC_NOISE = 845,
    MOVE_UPPER_HAND = 846,
    MOVE_MALIGNANT_CHAIN = 847,
    MOVES_COUNT_GEN9,


    // Add any custom moves here, not further down!

    MOVES_COUNT = MOVES_COUNT_GEN9,

    // Z Moves
    FIRST_Z_MOVE = MOVES_COUNT,
    MOVE_BREAKNECK_BLITZ = FIRST_Z_MOVE,
    MOVE_ALL_OUT_PUMMELING,
    MOVE_SUPERSONIC_SKYSTRIKE,
    MOVE_ACID_DOWNPOUR,
    MOVE_TECTONIC_RAGE,
    MOVE_CONTINENTAL_CRUSH,
    MOVE_SAVAGE_SPIN_OUT,
    MOVE_NEVER_ENDING_NIGHTMARE,
    MOVE_CORKSCREW_CRASH,
    MOVE_INFERNO_OVERDRIVE,
    MOVE_HYDRO_VORTEX,
    MOVE_BLOOM_DOOM,
    MOVE_GIGAVOLT_HAVOC,
    MOVE_SHATTERED_PSYCHE,
    MOVE_SUBZERO_SLAMMER,
    MOVE_DEVASTATING_DRAKE,
    MOVE_BLACK_HOLE_ECLIPSE,
    MOVE_TWINKLE_TACKLE,
    // Signature Z Moves
    MOVE_CATASTROPIKA,
    MOVE_10000000_VOLT_THUNDERBOLT,
    MOVE_10_000_000_VOLT_THUNDERBOLT = MOVE_10000000_VOLT_THUNDERBOLT,
    MOVE_STOKED_SPARKSURFER,
    MOVE_EXTREME_EVOBOOST,
    MOVE_PULVERIZING_PANCAKE,
    MOVE_GENESIS_SUPERNOVA,
    MOVE_SINISTER_ARROW_RAID,
    MOVE_MALICIOUS_MOONSAULT,
    MOVE_OCEANIC_OPERETTA,
    MOVE_SPLINTERED_STORMSHARDS,
    MOVE_LETS_SNUGGLE_FOREVER,
    MOVE_CLANGOROUS_SOULBLAZE,
    MOVE_GUARDIAN_OF_ALOLA,
    MOVE_SEARING_SUNRAZE_SMASH,
    MOVE_MENACING_MOONRAZE_MAELSTROM,
    MOVE_LIGHT_THAT_BURNS_THE_SKY,
    MOVE_SOUL_STEALING_7_STAR_STRIKE,
    LAST_Z_MOVE = MOVE_SOUL_STEALING_7_STAR_STRIKE,
    MOVES_COUNT_Z,

    // Max Moves
    FIRST_MAX_MOVE = MOVES_COUNT_Z,
    MOVE_MAX_GUARD = FIRST_MAX_MOVE,
    MOVE_MAX_STRIKE,
    MOVE_MAX_KNUCKLE,
    MOVE_MAX_AIRSTREAM,
    MOVE_MAX_OOZE,
    MOVE_MAX_QUAKE,
    MOVE_MAX_ROCKFALL,
    MOVE_MAX_FLUTTERBY,
    MOVE_MAX_PHANTASM,
    MOVE_MAX_STEELSPIKE,
    MOVE_MAX_FLARE,
    MOVE_MAX_GEYSER,
    MOVE_MAX_OVERGROWTH,
    MOVE_MAX_LIGHTNING,
    MOVE_MAX_MINDSTORM,
    MOVE_MAX_HAILSTORM,
    MOVE_MAX_WYRMWIND,
    MOVE_MAX_DARKNESS,
    MOVE_MAX_STARFALL,
    // Gigantamax Moves
    //MOVE_G_MAX_VINE_LASH,
    MOVE_ROOT_BIND,//digi move, replaces g max vine lash
    MOVE_G_MAX_WILDFIRE,
    MOVE_G_MAX_CANNONADE,
    MOVE_G_MAX_BEFUDDLE,
    MOVE_G_MAX_VOLT_CRASH,
    MOVE_G_MAX_GOLD_RUSH,
    MOVE_G_MAX_CHI_STRIKE,
    MOVE_G_MAX_TERROR,
    MOVE_G_MAX_FOAM_BURST,
    MOVE_G_MAX_RESONANCE,
    MOVE_G_MAX_CUDDLE,
    MOVE_G_MAX_REPLENISH,
    MOVE_G_MAX_MALODOR,
    MOVE_G_MAX_MELTDOWN,
    MOVE_G_MAX_DRUM_SOLO,
    MOVE_G_MAX_FIREBALL,
    MOVE_G_MAX_HYDROSNIPE,
    MOVE_G_MAX_WIND_RAGE,
    MOVE_G_MAX_GRAVITAS,
    MOVE_G_MAX_STONESURGE,
    MOVE_G_MAX_VOLCALITH,
    MOVE_G_MAX_TARTNESS,
    MOVE_G_MAX_SWEETNESS,
    MOVE_G_MAX_SANDBLAST,
    MOVE_G_MAX_STUN_SHOCK,
    MOVE_G_MAX_CENTIFERNO,
    MOVE_G_MAX_SMITE,
    MOVE_G_MAX_SNOOZE,
    MOVE_G_MAX_FINALE,
    MOVE_G_MAX_STEELSURGE,
    MOVE_G_MAX_DEPLETION,
    MOVE_G_MAX_ONE_BLOW,
    MOVE_G_MAX_RAPID_FLOW,
    LAST_MAX_MOVE = MOVE_G_MAX_RAPID_FLOW,
    MOVES_COUNT_DYNAMAX,
    MOVES_COUNT_ALL = MOVES_COUNT_DYNAMAX,

//this section replaces instances of the vanilla moves with the digimon moves, so the data doesnt need to be changed throughout. preverses compatibility with the main branch. 
//also because i'm adding SO MANY moves, and SO MANY ITEMS, the compile doesnt like it. so im replacing them instead as much as possible

//--------neutral-------------------------------
#define MOVE_BUBBLE MOVE_BUBBLES                    //30 power special move
#define MOVE_ICY_WIND MOVE_ADHESIVE_BUBBLE          //30 power special move, lowers speed
#define MOVE_MACH_PUNCH MOVE_MACH_JAB				//40 power physical move, +1 priority
#define MOVE_POUND MOVE_STRIKE                      //45 power physical move
#define MOVE_SLAM MOVE_HEAVY_STRIKE                 //60 power physical move, 95% accuracy, high crit ratio
#define MOVE_MEGA_PUNCH MOVE_MEGATON_PUNCH          //80 power physical move, 85% accuracy
#define MOVE_DOUBLE_SLAP MOVE_SUPER_SLAP            //20 power physical multi hit move
#define MOVE_DOUBLESLAP MOVE_SUPER_SLAP
#define MOVE_RAPID_SPIN MOVE_SPIRAL_EDGE			//50 power physical move, rapid-spin effect
#define MOVE_WORK_UP MOVE_ATTACK_CHARGE				//status, +1 attack to one target
#define MOVE_AROMATIC_MIST MOVE_MENTAL_CHARGE		//status, +1 sp attack to one target
#define MOVE_SHARPEN MOVE_MUSCLE_CHARGE				//status, +1 attack and sp attack to the user
#define MOVE_HARDEN MOVE_GUARD_CHARGE				//status, +1 defense to one target
#define MOVE_GROWTH MOVE_MAGIC_CHARGE				//status, +1 sp defense to one target
#define MOVE_REFLECT MOVE_GUARD_FIELD				//status, puts up a reflect for 5 turns
#define MOVE_AGILITY MOVE_SPEED_CHARGE				//status, +1 speed to one target
#define MOVE_FOCUS_ENERGY MOVE_CRITICAL_CHARGE		//status, +1 crit rate to the user
#define MOVE_MINIMIZE MOVE_MASS_MORPH				//status, +1 evasiveness to the target
#define MOVE_LEER MOVE_GUARD_BREAK					//status, -1 defence to both foes
#define MOVE_CONSTRICT MOVE_SPEED_BREAK				//status, -1 speed to both foes
#define MOVE_HEAL_PULSE MOVE_HEAL					//status, restores 50% of the target's health
#define MOVE_REFRESH MOVE_MEDITATOR					//status, heals status on the target
//--------fire-------------------------------
#define MOVE_EMBER MOVE_SPITFIRE                    //40 power special move, +1 priority
#define MOVE_FLAME_BURST MOVE_FIRE_BALL             //50 power physical move, can burn
#define MOVE_INCINERATE MOVE_BLUE_BLASTER			//50 power special move, can -1 sp defence
#define MOVE_FLAME_WHEEL MOVE_GOBLIN_STRIKE			//40 power physical move, 75% chance to -1 defence
#define MOVE_HEAT_WAVE MOVE_FRIENDLY_FIRE           //60 power special move, damages everyone but user, chance to burn.
#define MOVE_BURNING_BULWARK MOVE_FIREWALL			//status. Protect, but causes burns on contact.
#define MOVE_WILL_O_WISP MOVE_PANIC_WISP            //status 85% accuracy, burns the target
//--------water-------------------------------
//      MOVE_SPLASH                                 //230 power physical move. +1 speed
#define MOVE_BUBBLE_BEAM MOVE_BUBBLE_BREATH         //50 power special move
#define MOVE_BUBBLEBEAM MOVE_BUBBLE_BREATH
#define MOVE_WATER_PULSE MOVE_WATER_TOWER           //50 power physical move
#define MOVE_CUT MOVE_SCISSOR_ATTACK				//40 power physical move. x2 on status'd foes
#define MOVE_SING MOVE_LULLABY_BUBBLE				//45 power special move, chance to cause sleep
#define MOVE_SURF MOVE_TIDAL_STREAM					//60 power special move, hits both foes
#define MOVE_WATER_SHURIKEN MOVE_MARCHING_FISH		//25 power physical move, multi-hit
//      MOVE_WATERFALL                              //80 power physical move, can cause flinching.
#define MOVE_HYPNOSIS MOVE_IDLE_BUBBLE              //10 power 60% accuracy special move, puts the target to sleep
#define MOVE_WATER_SPORT MOVE_AQUA_MAGIC            //status move, +1 special attack
#define MOVE_RAIN_DANCE MOVE_HEAVY_RAIN             //status move, summons rain. 
//--------plant-------------------------------
#define MOVE_VINE_WHIP MOVE_THORN_STRIKE			//45 power special move
#define MOVE_BRANCH_POKE MOVE_RAIN_OF_POLLEN		//50 power special move. lowers evasiveness
#define MOVE_G_MAX_VINE_LASH MOVE_ROOT_BIND			//25 power physical move. causes vine lash vortex
#define MOVE_RAZOR_LEAF MOVE_BIO_HAZARD				//60 power special move, hurts both foes, may cause poison
#define MOVE_SLUDGE MOVE_VENOM_TRAP					//40 power special move. may cause poison. 
#define MOVE_POISON_JAB MOVE_POISON_IVY				//60 power physcial move. may cause paralysis 
#define MOVE_MAGICAL_LEAF MOVE_CRESCENT_LEAF		//60 power special move. can't miss
//      MOVE_POISON_POWDER                          //sttaus. causes poison. Unchanged from vanilla
//--------Insect------------------------------
#define MOVE_STRING_SHOT MOVE_ELECTRO_THREAD		//20 power special move, may paralyse
#define MOVE_ATTACK_ORDER MOVE_INSECT_HORDE			//5 power special move, can hit up to 10 
#define MOVE_SPIDER_WEB MOVE_STICKY_NET				//status, prevents foe from switching 
//--------beast------------------------------
#define MOVE_ROCK_THROW MOVE_COMET_HAMMER			//40 power physical move
#define MOVE_ROLLOUT MOVE_SPIN_ATTACK				//30 power physical move, rapid spin effect
//--------metal-------------------------------
#define MOVE_THUNDER_SHOCK MOVE_HERTZ_HOWL          //30 power special move, may paralyze
#define MOVE_METAL_CLAW MOVE_IRON_SLASH             //55 power physcial move, high crit ratio
#define MOVE_THUNDERSHOCK MOVE_HERTZ_HOWL
#define MOVE_DOUBLE_IRON_BASH MOVE_CRUSH_BLADE      //50 power physical move, prevents foe's escape
#define MOVE_MAGNET_BOMB MOVE_DIS_ASSEMBLER         //60 power special move. cant miss
// MOVE_MECHANICAL_CLAW powerful physical move
// MOVE_GIGAWATT LASER //powerful special move. 
// MOVE_DELETE_PROGRAM //status. causes a curse effect that kills the foe over several turns. 
// MOVE_DG_DIMENSION //a room effect or custom weather
// MOVE UPGRADE //status move. boosts stats
// MOVE_ANTI_ATTACK //status. lowers attack of both foes. 

//--------earth-------------------------------
#define MOVE_COMET_PUNCH MOVE_SHAMA_HAMMER	        //45 power physical move, reduces foes attack. 
#define MOVE_ANCIENTPOWER MOVE_GAIA_BLAST           //50 power special move.
#define MOVE_ANCIENT_POWER MOVE_GAIA_BLAST
#define MOVE_SMACK_DOWN MOVE_ROCK_FIST              //50 power physical move. may flinch
//--------electric-------------------------------
#define MOVE_BUZZY_BUZZ MOVE_NANOBOT_BREAK          //45 power physical move, can't miss
#define MOVE_THUNDERPUNCH MOVE_THUNDER_STRIKE       //50 power physical move, 10% chance to paralyze
#define MOVE_THUNDER_PUNCH MOVE_THUNDER_STRIKE
#define MOVE_SHOCK_WAVE MOVE_ELECTRO_SHOCK          //50 power special move, 20% chance to paralyze
#define MOVE_SPARK MOVE_MINI_SCISSOR_CLAW           //55 power physical move, high crit rate
#define MOVE_THUNDER_WAVE MOVE_ELECTRIC_CLOUD       //status move, paralyses the target
//      MOVE_ELECTRIC_TERRAIN   //status move. summons electric terrain
//--------wind-------------------------------  
#define MOVE_GUST MOVE_AIR_BUBBLES                  //40 power special move
#define MOVE_PECK MOVE_WIND_CLAW                    //50 power physical move
#define MOVE_QUICK_ATTACK MOVE_SONIC_JAB            //40 power physical move, +1 priority
#define MOVE_AIR_CUTTER MOVE_AIR_SHOT               //55 power special move, high crit ratio
#define MOVE_TWISTER MOVE_DARK_TWISTER				//50 power physical move, hits both foes. may cause flinching
#define MOVE_AIR_SLASH MOVE_WIND_CUTTER             //80 power physical move, high crit ratio. hits both foes.
// MOVE_HURRICANE                                   //80 power special move. hits both foes. 
#define MOVE_WILDBOLT_STORM MOVE_THUNDERSTORM       //110 power special, hits both foes, may paralyze
#define MOVE_FEATHERDANCE MOVE_WING_SHOES           //status. sharply boosts the target's speed
#define MOVE_FEATHER_DANCE MOVE_WING_SHOES
//      MOVE_TAILWIND                               //Status. same as vanilla. boosts the speed of the users team for 4 turns.
//--------ice-------------------------------
#define MOVE_POWDER_SNOW MOVE_FROZEN_WIND			//50 power special move, may freeze
#define MOVE_ICE_SHARD MOVE_FROZEN_BULLET			//40 power special move, +1 priority
#define MOVE_ICE_BALL MOVE_ICY_GLIDE                //60 power physical move, +1 priority if snowing
#define MOVE_AVALANCHE MOVE_DIAMOND_DUST			//20 power physical multi strike
#define MOVE_ICE_PUNCH MOVE_SNOW_GOBLI_VOLT			//45 power physical move, may freezetimes
#define MOVE_ICICLE_SPEAR MOVE_HAIL_SPEAR           //25 power physical move, multi-hit
#define MOVE_FREEZY_FROST MOVE_ICE_STATUE           //80 power physical move, may cause frostbite
#define MOVE_AURORA_BEAM MOVE_AURORA_FREEZE         //status, causes frostbite
//--------dark-------------------------------
#define MOVE_NIGHT_SHADE MOVE_NIGHTMARE_SYNDROME	//60 power physical move, may sleep
#define MOVE_LICK MOVE_DARK_SPIRIT					//40 power special move
#define MOVE_FAINT_ATTACK MOVE_HELL_CRUSHER			//60 power physical move, hits both foes
#define MOVE_FEINT_ATTACK MOVE_HELL_CRUSHER
#define MOVE_SCRATCH MOVE_NAIL_SCRATCH				//30 power physical move
#define MOVE_GEAR_GRIND MOVE_COG_CRUSH				//50 power physical move
#define MOVE_ABSORB MOVE_HUNGRY_HAND				//50 power physical move, absorbs health
#define MOVE_CONFUSE_RAY MOVE_BLACKOUT				//status, causes confusion
#define MOVE_GROWL MOVE_BAD_MANNERS					//status, lowers both foes attack
//--------Light-------------------------------
//      MOVE_FLASH                                  //30 power, special move. reduces accuracy
#define MOVE_DISARMING_VOICE MOVE_HOLY_LIGHT		//40 power, special move
#define MOVE_PSYWAVE MOVE_LIGHT_SOUL                //40 power, physical move
// MOVE_SAINT_RAY //60 power special move
// MOVE_ANGEL_ROD
// MOVE_HAND_OF_FATE
// MOVE_HOLY_BREATH  //status, boosts special attack and special defence 
// MOVE_SAINT_SHIELD //Status, protect variant. 
// MOVE_JUDGEMENT //high power physical move. 
// MOVE_SHINING_NOVA //high power special move, hits both foes, may burn. 
//--------puppet-------------------------------
#define MOVE_TAIL_SLAP MOVE_FOX_TAIL				//40 power, physical move
//--------undead-------------------------------
#define MOVE_ASTONISH MOVE_CANDLE_SLASH				//40 power physical move, may burn
//--------filth-------------------------------
#define MOVE_EGG_BOMB MOVE_CHEESE_BOMB				//40 power physical move
#define MOVE_ACID MOVE_POOP_THROW					//40 power special move
#define MOVE_POISON_STING MOVE_DANGER_STING			//30 power physical move. +1 priority
#define MOVE_POISON_FANG MOVE_POISON_CLAW			//30 power physical move. may poison
#define MOVE_SMOG MOVE_GLOOM_DUST					//30 power Special move, may poison
#define MOVE_DIRE_CLAW MOVE_FUNGUS_CRUSHER			//50 power physical move. 30% chance to cause sleep, poison or paralysis
//cooties kick  //physical move. mega kick equivalent. 75 power, 85% accuracy
//super stink jet //special move that causes the block effect, preventing item use
//poop field //custom terrain. 
//Guerilla poop //high power physical move. 



};

#define MOVE_DEFAULT     0x3FFF // Used when creating a mon to be replaced by a level-up move (needs to be less than that 0x4000 because of VarGet)
#define MOVE_UNAVAILABLE 0xFFFF // Used for checks for moves affected by Disable, Mimic, etc.



#endif  // GUARD_CONSTANTS_MOVES_H
