gText_Birch_Welcome::
	.string "Hi!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is a work in progress!\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "At the moment, you should be able to play\n"
	.string "up until you reach Petalburg.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "And you are?$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatsYourName::
	.string "All right.\n"
	.string "What's your name?$"

gText_Birch_SoItsPlayer::
	.string "So it's {PLAYER}{KUN}?$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Get in on it\p"
	.string "$"
